export default {
  ru: {
    "login.email": "Email",
    "login.pass": "Пароль",
    "login.login": "Вход",
    "profile.update": "Обновить",
    ok_success: "Задача запущена",
    err_order_exist: "Ваша задача выполняется! Cледующию задачу можно будет запустить после завершения",
    err_of_login: "Ошибка входа в систему",
    err_user_not_exist: "Такой пользователь не был зарегестрирован",
    err_pass: "Неправильный пароль",
    err_empty_fullname: "Пустое поле имени",
    err_empty_user: "Пустое поле Email адреса",
    err_not_email: "Неправильно введен Email",
    err_pass_lenth: "Пароль должен быть от 4 до 10 символов",
    ok_success_login: "Вы вошли в систему",
    "profile.exit": "Выйти",
  },
  en: {
    "login.email": "Email",
    "login.pass": "Password",
    "login.login": "Login",
    "profile.update": "Update",
    ok_success: "Задача запущена",
    err_order_exist: "Ваша задача выполняется! Cледующию задачу можно будет запустить после завершения",
    err_of_login: "Ошибка входа в систему",
    err_user_not_exist: "Такой пользователь не был зарегестрирован",
    err_pass: "Неправильный пароль",
    err_empty_fullname: "Пустое поле имени",
    err_empty_user: "Пустое поле Email адреса",
    err_not_email: "Неправильно введен Email",
    err_pass_lenth: "Пароль должен быть от 4 до 10 символов",
    ok_success_login: "Вы вошли в систему",
    "profile.exit": "Выйти",
  },
};
