export default {
  ru: {
    "login.email": "Введите email",
    "login.pass": "Введите пароль",
    "login.login": "Вход",
    err_of_registration: "Ошибка регестрации",
    err_of_login: "Ошибка входа в систему",
    err_user_exist: "Такой пользователь уже был зарегестрирован",
    err_user_not_exist: "Такой пользователь не был зарегестрирован",
    err_pass: "Неправильный пароль",
    err_empty_fullname: "Пустое поле имени",
    err_empty_user: "Пустое поле Email адреса",
    err_not_email: "Неправильно введен Email",
    err_pass_lenth: "Пароль должен быть от 4 до 10 символов",
    ok_success_login: "Вы вошли в систему",
  },
  en: {
    "login.email": "Email",
    "login.pass": "Password",
    "login.login": "Login",
    err_of_registration: "Ошибка регестрации",
    err_of_login: "Ошибка входа в систему",
    err_user_exist: "Такой пользователь уже был зарегестрирован",
    err_user_not_exist: "Такой пользователь не был зарегестрирован",
    err_pass: "Неправильный пароль",
    err_empty_fullname: "Пустое поле имени",
    err_empty_user: "Пустое поле Email адреса",
    err_not_email: "Неправильно введен Email",
    err_pass_lenth: "Пароль должен быть от 4 до 10 символов",
    ok_success_login: "Вы вошли в систему",
  },
};
